const CartActionTypes = {
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART_ITEM: "CLEAR_CART_ITEM",
  EMPTY_CART: "EMPTY_CART",
  POPULATE_CART_ITEMS: "POPULATE_CART_ITEMS",
};

export default CartActionTypes;
